### ISSUE TITLE
Website not reachable

### ISSUE THREAD

**Issue by kumarshantanu** [mheath/adbcj#1]
The website adbcj.org is not reachable - it shows an OpenDNS page. Also, there is no README in the repo that makes it hard to know what the project is about at a glance.

**Comment by lukaseder** [comment]
I second this, the website http://adbcj.org is not available. In fact, the domain is available...

**Comment by mheath** [comment]
The adbcj.org domain name has long expired and I have not plans to renew it. I did however add a README.md which is long over due. Thanks @lukaseder for kicking me in the butt to do something about this. :)

**Comment by lukaseder** [comment]
Well done, @mheath :)
But the link is still there in the project description:

![image](https://cloud.githubusercontent.com/assets/734593/8200501/32a90b7a-14c6-11e5-859f-04aaa551a4ff.png)

**Comment by mheath** [comment]
Oops. Thanks. Fixed that too.
